
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AGGREGATION ARROW_LR ARROW_RL ASTERISK AT BOOLEAN_TYPE BOOLEAN_VALUE BRINGSABOUT CATEGORY CHARACTERIZATION CLASS CLASS_NAME COLLECTIVE COLON COMMA COMPARATIVE COMPLETE COMPONENTOF COMPOSITION CONST CONSTITUTION CREATION DATETIME_LITERAL DATETIME_TYPE DATE_LITERAL DATE_TYPE DERIVATION DERIVED DISJOINT DOTDOT DOUBLE_HYPHEN EVENT EXTERNALDEPENDENCE EXTRINSICMODE FORMAL FUNCTIONALCOMPLEXES GENERAL GENSET HISTORICALDEPENDENCE HISTORICALROLE HISTORICALROLEMIXIN IMPORT INHERENCE INSTANCE_NAME INSTANTIATION INTRISICMODE KIND LBRACE LBRACKET LPAREN MANIFESTATION MATERIAL MEDIATION MEMBEROF MIXIN MODE NEW_DATATYPE NUMBER NUMBER_TYPE ORDERED PACKAGE PARTICIPATION PARTICIPATIONAL PHASE PHASEMIXIN PROCESS QUALITY QUANTITY RBRACE RBRACKET REDEFINES RELATION_NAME ROLE ROLEMIXIN RPAREN SITUATION SPECIALIZES SPECIFICS STRING STRING_TYPE SUBCOLLECTIONOF SUBKIND SUBQUALITYOF SUBSETS TERMINATION TIME_LITERAL TIME_TYPE TRIGGERS VALUE WHEREprograma : pre_package_decls declaracao_package declaracoes_pos_packagepre_package_decls : pre_package_decls import_decl\n| emptyimport_decl : IMPORT CLASS_NAMEdeclaracao_package : PACKAGE CLASS_NAMEdeclaracoes_pos_package : declaracoes_pos_package declaracao_restante\n| emptydeclaracao_restante : tipo_simples CLASS_NAME\n| declaracao_genset\n| declaracao_relacaotipo_simples : KINDdeclaracao_genset : GENSET CLASS_NAMEdeclaracao_relacao : RELATION_NAMEempty :'
    
_lr_action_items = {'PACKAGE':([0,2,3,5,11,],[-14,6,-3,-2,-4,]),'IMPORT':([0,2,3,5,11,],[-14,7,-3,-2,-4,]),'$end':([1,4,8,9,10,12,14,15,18,19,20,],[0,-14,-1,-7,-5,-6,-9,-10,-13,-8,-12,]),'KIND':([4,8,9,10,12,14,15,18,19,20,],[-14,16,-7,-5,-6,-9,-10,-13,-8,-12,]),'GENSET':([4,8,9,10,12,14,15,18,19,20,],[-14,17,-7,-5,-6,-9,-10,-13,-8,-12,]),'RELATION_NAME':([4,8,9,10,12,14,15,18,19,20,],[-14,18,-7,-5,-6,-9,-10,-13,-8,-12,]),'CLASS_NAME':([6,7,13,16,17,],[10,11,19,-11,20,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'pre_package_decls':([0,],[2,]),'empty':([0,4,],[3,9,]),'declaracao_package':([2,],[4,]),'import_decl':([2,],[5,]),'declaracoes_pos_package':([4,],[8,]),'declaracao_restante':([8,],[12,]),'tipo_simples':([8,],[13,]),'declaracao_genset':([8,],[14,]),'declaracao_relacao':([8,],[15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> pre_package_decls declaracao_package declaracoes_pos_package','programa',3,'p_programa','parser.py',22),
  ('pre_package_decls -> pre_package_decls import_decl','pre_package_decls',2,'p_pre_package_decls','parser.py',40),
  ('pre_package_decls -> empty','pre_package_decls',1,'p_pre_package_decls','parser.py',41),
  ('import_decl -> IMPORT CLASS_NAME','import_decl',2,'p_import_decl','parser.py',55),
  ('declaracao_package -> PACKAGE CLASS_NAME','declaracao_package',2,'p_declaracao_package','parser.py',67),
  ('declaracoes_pos_package -> declaracoes_pos_package declaracao_restante','declaracoes_pos_package',2,'p_declaracoes_pos_package','parser.py',80),
  ('declaracoes_pos_package -> empty','declaracoes_pos_package',1,'p_declaracoes_pos_package','parser.py',81),
  ('declaracao_restante -> tipo_simples CLASS_NAME','declaracao_restante',2,'p_declaracao_restante','parser.py',91),
  ('declaracao_restante -> declaracao_genset','declaracao_restante',1,'p_declaracao_restante','parser.py',92),
  ('declaracao_restante -> declaracao_relacao','declaracao_restante',1,'p_declaracao_restante','parser.py',93),
  ('tipo_simples -> KIND','tipo_simples',1,'p_tipo_simples','parser.py',99),
  ('declaracao_genset -> GENSET CLASS_NAME','declaracao_genset',2,'p_declaracao_genset','parser.py',103),
  ('declaracao_relacao -> RELATION_NAME','declaracao_relacao',1,'p_declaracao_relacao','parser.py',107),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',114),
]
